import express from "express";
import { authenticate, authorize } from "../middleware/authMiddleware.js";
import * as operations from "../controllers/operationsController.js";

const router = express.Router();
router.use(authenticate);
router.use(authorize("ADMIN", "MANAGER", "HEAD_LADY", "BAR", "KITCHEN", "WAITER"));
router.get("/bootstrap", operations.getBootstrap);
router.get("/dashboard", authorize("ADMIN", "MANAGER"), operations.getDashboard);
router.get("/reports", authorize("ADMIN", "MANAGER"), operations.getReports);
router.get("/orders", operations.getOrders);
router.post("/orders", authorize("WAITER"), operations.createOrder);
router.patch("/orders/:id/status", authorize("KITCHEN", "WAITER"), operations.updateOrderStatus);
router.patch("/orders/:id/fulfillment", authorize("BAR", "KITCHEN"), operations.updateFulfillmentStatus);
router.post("/menu", authorize("MANAGER"), operations.createMenuItem);
router.patch("/menu/:id", authorize("MANAGER"), operations.updateMenuItem);
router.patch("/menu/:id/availability", authorize("MANAGER", "KITCHEN"), operations.updateDailyMenuAvailability);
router.delete("/menu/:id", authorize("MANAGER"), operations.deleteMenuItem);
router.post("/inventory", authorize("MANAGER"), operations.createInventory);
router.post("/inventory/:id/adjust", authorize("MANAGER"), operations.adjustInventory);
router.patch("/inventory/:id/daily-status", authorize("BAR", "KITCHEN"), operations.updateDepartmentInventoryStatus);
router.post("/employees", authorize("MANAGER"), operations.createEmployee);
router.patch("/employees/:id", authorize("MANAGER"), operations.updateEmployee);
router.delete("/employees/:id", authorize("MANAGER"), operations.deleteEmployee);
router.post("/employees/:id/attendance", authorize("MANAGER"), operations.toggleAttendance);
router.post("/customers", authorize("MANAGER"), operations.createCustomer);
router.post("/rooms", authorize("MANAGER"), operations.createRoom);
router.get("/rooms/:id/details", authorize("ADMIN", "MANAGER", "HEAD_LADY"), operations.getRoomDetails);
router.post("/rooms/:id/sessions", authorize("HEAD_LADY"), operations.startRoomSession);
router.patch("/room-sessions/:id/end", authorize("HEAD_LADY"), operations.endRoomSession);
router.post("/room-sessions/:id/attendants", authorize("HEAD_LADY"), operations.assignRoomAttendant);
router.patch("/room-attendants/:id/end", authorize("HEAD_LADY"), operations.endRoomAttendant);
router.patch("/rooms/:id", authorize("MANAGER"), operations.updateRoom);
router.delete("/rooms/:id", authorize("MANAGER"), operations.deleteRoom);
export default router;
